### ISSUE TITLE
How did you obtain the api links

### ISSUE THREAD

**Issue by MCTRACO** [mattogodoy/rockfm-monitor#1]
DO you still have them, if so, please can you write them here, they would be very helpful for me, thanks

**Comment by mattogodoy** [comment]
Hello! All I did was to go to the radio's online player and capture the calls it was making. That's how I got this URL:
https://github.com/mattogodoy/rockfm-monitor/blob/master/monitor.py#L55

After that all I had to do is call the same endpoint to obtain the data :)

**Comment by MCTRACO** [comment]
Ok thanks; but do you have any more links related to the api thanks again

**Comment by mattogodoy** [comment]
Nope, since I only needed that one I don't have any further information about that API.

**Comment by MCTRACO** [comment]
Ok thanks because with the link you provided i can see the title and the author but it doesnt provide the insge shown link, i will investigate more but thanks anyways

**Comment by MCTRACO** [comment]
YEsss, i know how to get the image :
https://www.rockfm.fm/app/track/{track} with that response substituting the word in brackets by the track you want the image from.
I dont know how to thank you, for giving me this wonderful idea, you are the best

**Comment by mattogodoy** [comment]
Cool! I'm glad you found a way 😃
